### PR TITLE
Search all collections

### PR DESCRIPTION
**Pull request by ashwinvis**

### CODE REVIEW

**Comment by kensanata** [comment]
I think the simple question I have is whether we need to add `itertools` to `install_requires` in `setup.py`? If so, can you add that?

I have a different question regarding the order in which results are displayed, however. I *feel* like I'd like search results from multiple collections to present results in order of creation, irrespective of where they were found. I don't even know what that means. Should we sort the statuses found at the end? Should we assume that the statuses in collections are ordered (they will be, almost always, I think?) and thus merge all the collections first and *then* search them? Or were you yourself just interested in finding *one* status and just the question of sort order just never comes up?

**Comment by kensanata** [comment]
Merging, because it's better than what we have, but I still wonder. :)

**Comment by kensanata** [comment]
I guess [itertools](https://docs.python.org/3/library/itertools.html) is part of the core.

**Comment by ashwinvis** [comment]
> Or were you yourself just interested in finding one status and just the question of sort order just never comes up?

That's it. I find myself searching for a keyword and I am always unsure what collection it was in.

>  Should we sort the statuses found at the end? Should we assume that the statuses in collections are ordered (they will be, almost always, I think?) and thus merge all the collections first and then search them? 

Merging (by `dict.update`) and sorting (`sorted`) would be nice. But I doubt if it would be that simple.

**Comment by kensanata** [comment]
OK, we'll leave it as it is. If somebody misses the feature, we can always add it later.

**Pull request merged**
