### PR TITLE
add contrib: wrapper script to ease usage, install debs via Debian packages

### LINKED ISSUE #78: Install "the Debian way"
As discussed at Mastodon, here a short "guide" how I installed mastodon-backup without running `setup.py`:

First install dependencies: `apt install python3-progress python3-mastodon`. Then, inside the cloned repo's root, create a wrapper (e.g. `mastodon.py`) looking like this:

```python
#!/usr/bin/env python3
import mastodon_archive

if __name__ == "__main__":
  mastodon_archive.main()
```

Make it executable, create an alias for it (`alias mastodon-archive="$HOME/bin/mastodon-backup/mastodon-archive.py"`) or add a wrapper script to our `$PATH` containing just `$HOME/bin/mastodon-backup/mastodon-archive.py $*` (adjust the path to where you put the cloned repo to), and we are ready to go.

If now running `mastodon-archive archive --with-mentions <account>` fails with `AttributeError: 'Mastodon' object has no attribute 'bookmarks'`, your distribution shipped an older version of `python3-mastodon` (Ubuntu 20.04 and derivates: 1.5.0). In this case, get the 1.5.1 [from PyPi](https://pypi.org/project/Mastodon.py/1.5.1/) and replace the files in `/usr/lib/python3/dist-packages/mastodon`.

Done.

### PR DESCRIPTION
**Pull request by IzzySoft**
Starting on the contrib scripts. This will entail 2 scripts:

* a wrapper script (`mastoarch`) to ease and automate things
* an installer script for a more "Debian-like" install (using packages instead of PyPi), see #78 

closes #78

### CODE REVIEW

**Comment by kensanata** [comment]
Thanks!

**Comment by lapineige** [comment]
What does this wrapper do ?

**Comment by IzzySoft** [comment]
@lapineige just run it without parameters, it will tell you. For details, you can see e.g. [here](https://android.izzysoft.de/articles/named/fediverse-2#backups).

**Comment by kensanata** [comment]
Maybe it would be a good idea to leave a pointer in the main README so that people remember to go and check?

**Comment by IzzySoft** [comment]
Maybe we also should add a README inside the `contrib/` directory to point out details on what is there? Then the hint in the main README could be as simple as "also read that" :wink:

**Comment by kensanata** [comment]
Sounds good to me!

**Comment by IzzySoft** [comment]
OK, will do then as soon as time permits. But first I'm out inti the sunlight now – don't want to waste that nice weather we currently have :smiley:

**Pull request merged**
